Index: asBIM/Cls_SetMaxMinPtToElements/Code_SetMaxMinPtToElements.cs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.BaseRevisionTextPatchEP
<+>using Autodesk.Revit.Attributes;\r\nusing Autodesk.Revit.DB;\r\nusing Autodesk.Revit.UI;\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing System.Linq;\r\nusing System.Text;\r\nusing System.Threading.Tasks;\r\nusing asBIM.Properties;\r\nusing System.Windows.Data;\r\nusing System.Collections.ObjectModel;\r\nusing System.Xaml;\r\nusing System.Windows.Documents;\r\nusing System.Xml.Linq;\r\nusing System.Windows;\r\nusing Notifications.Wpf;\r\n\r\n\r\nnamespace asBIM\r\n{\r\n    [TransactionAttribute(TransactionMode.Manual)]\r\n    [RegenerationAttribute(RegenerationOption.Manual)]\r\n\r\n    public class Code_SetMaxMinPtToElements : IExternalCommand\r\n    {\r\n        public Result Execute(ExternalCommandData commandData, ref string message, ElementSet elements)\r\n        {\r\n            var uiapp = commandData.Application;\r\n            var uidoc = uiapp.ActiveUIDocument;\r\n            var doc = uidoc.Document;\r\n\r\n            // ОСНОВНОЙ КОД ПЛАГИНА // НАЧАЛО  \r\n            Form_SetMaxMinPtToElements form = new Form_SetMaxMinPtToElements();\r\n            form.ShowDialog();\r\n\r\n            SetElementsTBPoints(doc);\r\n            \r\n            // TODO: 4. Сделать вывод инфо: 1. Необработанные элементы, 2. Обработанные элементы, 3. Время работы команды\r\n            // Оповещение об успешной отработке команды\r\n            NotificationManagerWPF_SetMaxMinPtToElements.Success(success: message);\r\n            // Оповещение об ошибке\r\n            //NotificationManagerWPF_SetMaxMinPtToElements.Error(error: message);\r\n            // Оповещение о времени работы команды\r\n            \r\n            \r\n\r\n            // ОСНОВНОЙ КОД ПЛАГИНА // КОНЕЦ  \r\n            return Result.Succeeded;\r\n        }\r\n\r\n\r\n        // Метод SetElementsTBPoints\r\n        // TODO: 5. ОПИСАНИЕ ДЕЙСТВИЯ МЕТОДА \"SetElementsTBPoints\" С ЦИКЛОМ РИЧ ДОПОЛНИТЬ !!!\r\n        internal void SetElementsTBPoints(Document doc)\r\n        {\r\n            // Коллекция + словать с именем переменной groupedElements с фильтром на категорию и Элементы\r\n            var groupedElements = RevitAPI_Sort_ByCategory.SortElementByCategory(doc);\r\n\r\n            //Транзакция\r\n            using (Transaction tr = new Transaction(doc, \"Запись параметров отметок Верха и Низа\"))\r\n            {\r\n                tr.Start();\r\n                // Цикл с перебором всех элементов в коллекции\r\n                foreach (Element elemincollector in groupedElements[\"AR\"])\r\n                {\r\n                    try\r\n                    {\r\n                        //Получение \"Общего параметра по Guid\" из Revit в переменную topPointParam из эл в коллекции. Отметка верха\r\n                        Parameter topPointParam = elemincollector.get_Parameter(new Guid(\"22c86588-f717-403e-b1c6-1607cac39965\"));\r\n                        //Получение \"Общего параметра по Guid\" из Revit в переменную bottomPointParam параметра из эл в коллекции. Отметка низа\r\n                        Parameter bottomPointParam = elemincollector.get_Parameter(new Guid(\"b0ed44c1-724e-4301-b489-8d89c02acec5\")); \r\n                        \r\n                        // Проверка на null \"Общего параметра по Guid\" из Revit\r\n                        if (topPointParam != null && bottomPointParam != null)\r\n                        {\r\n                            // Фильтр на Уровни. Выборка из Документа только уровней.\r\n                            FilteredElementCollector levelsCollector = new FilteredElementCollector(doc).OfClass(typeof(Level));\r\n                            // Список levels с типом Level\r\n                            List<Level> levels = levelsCollector.Cast<Level>().OrderBy(level => level.Elevation).ToList();\r\n                            \r\n                            // ЗАПИСЬ УРОВНЯ ДЛЯ ОТМЕТКИ ВЕРХА\r\n                            // Получение отметки Верха элемента с каждого элемента в Документе.\r\n                            double elementTopPointElevationSm = ElementTopBottomPt.GetElementTopPoint(elemincollector).Z;\r\n                            // Присвоение closestLevelForTop результата метода FindBottomElemLevel\r\n                            // В метод FindBottomElemLevel подаются отметки Низа всех эл из groupedElements[\"AR\"] и отсортированный по возрастанию??? список уровней\r\n                            Level closestLevelForTop = LevelInfo.FindBottomElemLevel(elementTopPointElevationSm, levels);\r\n\r\n                            double elemTopPtElevFromLevel = Math.Abs(closestLevelForTop.Elevation - elementTopPointElevationSm);\r\n                            \r\n                            double elemTopPtElevFromLevelSm = UnitUtils.ConvertFromInternalUnits(elemTopPtElevFromLevel, UnitTypeId.Millimeters);\r\n                            // Округление topVal до 2 знаков после запятой\r\n                            double elemTopPtElevFromLevelSmRound = Math.Round(elemTopPtElevFromLevelSm, 2, MidpointRounding.AwayFromZero);\r\n                            // Запись Имени Нижнего этажа.\r\n                            topPointParam.Set(closestLevelForTop != null ? elemTopPtElevFromLevelSmRound  + \" от \" + closestLevelForTop.Name : \"Не определено\");\r\n                            // ЗАПИСЬ УРОВНЯ ДЛЯ ОТМЕТКИ ВЕРХА\r\n                            \r\n                            \r\n                            // ЗАПИСЬ УРОВНЯ ДЛЯ ОТМЕТКИ НИЗА\r\n                            // Получение отметки Низа элемента с каждого элемента в Документе.\r\n                            double elementBottomPointElevationSm = ElementTopBottomPt.GetElementBottomPoint(elemincollector).Z;\r\n                            // Присвоение closestLevelForBot результата метода FindBottomElemLevel\r\n                            // В метод FindBottomElemLevel подаются отметки Низа всех эл из groupedElements[\"AR\"] и отсортированный по возрастанию??? список уровней\r\n                            Level closestLevelForBot = LevelInfo.FindBottomElemLevel(elementBottomPointElevationSm, levels);\r\n                            \r\n                            double elemBotPtElevFromLevel = Math.Abs(closestLevelForBot.Elevation - elementBottomPointElevationSm);\r\n                            \r\n                            double elemBotPtElevFromLevelSm = UnitUtils.ConvertFromInternalUnits(elemBotPtElevFromLevel, UnitTypeId.Millimeters);\r\n                            // Округление botVal до 2 знаков после запятой\r\n                            double elemBotPtElevFromLevelSmRound = Math.Round(elemBotPtElevFromLevelSm, 2, MidpointRounding.AwayFromZero);\r\n                            \r\n                            // Запись Имени Нижнего этажа.\r\n                            bottomPointParam.Set(closestLevelForBot != null ? elemBotPtElevFromLevelSmRound  + \" от \" + closestLevelForBot.Name : \"Не определено\");\r\n                            // ЗАПИСЬ УРОВНЯ ДЛЯ ОТМЕТКИ НИЗА\r\n                            \r\n                            \r\n                            \r\n                            // TODO: 6. Добавить конвертер наименований в Этаж №\r\n                        }\r\n                    }\r\n\r\n                    catch (Exception ex)\r\n                    {\r\n                        TaskDialog.Show(\"Ошибка\", ex.Message);\r\n                    }\r\n                }\r\n                tr.Commit();\r\n            }\r\n\r\n        }\r\n        \r\n        \r\n        //Метод для обнуления значений\r\n        internal void SetElementsTBPoints_Null(Document doc)\r\n        {\r\n            // Коллекция + словать с именем переменной groupedElements с фильтром на категорию и Элементы\r\n            var groupedElements = RevitAPI_Sort_ByCategory.SortElementByCategory(doc);\r\n        \r\n            //Транзакция\r\n            using (Transaction tr = new Transaction(doc, \"Запись параметров отметок Верха и Низа\"))\r\n            {\r\n                tr.Start();\r\n                // Цикл с перебором всех элементов в коллекции\r\n                foreach (Element elemincollector in groupedElements[\"AR\"])\r\n                {\r\n                    try\r\n                    {\r\n                        //Получение \"Общего параметра по Guid\" из Revit в переменную topPointParam из эл в коллекции. Отметка верха\r\n                        Parameter topPointParam = elemincollector.get_Parameter(new Guid(\"22c86588-f717-403e-b1c6-1607cac39965\"));\r\n                        //Получение \"Общего параметра по Guid\" из Revit в переменную bottomPointParam параметра из эл в коллекции. Отметка низа\r\n                        Parameter bottomPointParam = elemincollector.get_Parameter(new Guid(\"b0ed44c1-724e-4301-b489-8d89c02acec5\")); \r\n                        \r\n                        // Проверка на null \"Общего параметра по Guid\" из Revit\r\n                        if (topPointParam != null && bottomPointParam != null)\r\n                        {\r\n                            // ЗАПИСЬ УРОВНЯ ДЛЯ ОТМЕТКИ ВЕРХА\r\n                            topPointParam.Set(\"\");\r\n                            \r\n                            // ЗАПИСЬ УРОВНЯ ДЛЯ ОТМЕТКИ НИЗА\r\n                            bottomPointParam.Set(\"\");\r\n                        }\r\n                    }\r\n        \r\n                    catch (Exception ex)\r\n                    {\r\n                        TaskDialog.Show(\"Ошибка\", ex.Message);\r\n                    }\r\n                }\r\n                tr.Commit();\r\n            }\r\n        \r\n        }\r\n    }\r\n}\r\n\r\n
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/asBIM/Cls_SetMaxMinPtToElements/Code_SetMaxMinPtToElements.cs b/asBIM/Cls_SetMaxMinPtToElements/Code_SetMaxMinPtToElements.cs
--- a/asBIM/Cls_SetMaxMinPtToElements/Code_SetMaxMinPtToElements.cs	(revision 244c8ccdf08e48fbd0bbb06c6b31ae7582738cc9)
+++ b/asBIM/Cls_SetMaxMinPtToElements/Code_SetMaxMinPtToElements.cs	(date 1735232207912)
@@ -32,7 +32,7 @@
             // ОСНОВНОЙ КОД ПЛАГИНА // НАЧАЛО  
             Form_SetMaxMinPtToElements form = new Form_SetMaxMinPtToElements();
             form.ShowDialog();
-
+            if 
             SetElementsTBPoints(doc);
             
             // TODO: 4. Сделать вывод инфо: 1. Необработанные элементы, 2. Обработанные элементы, 3. Время работы команды
